[package]
name = "cvt-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Ratatui widget & screen layer for clash-verge-tui"

[dependencies]
cvt-core = { path = "../cvt-core", version = "0.8.4" }
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
ratatui = { workspace = true }
crossterm = { workspace = true }
futures-util = "0.3.34"
unicode-width = "0.2.2"
chrono.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile = "3"
serde_json.workspace = true
