[package]
name = "cvt"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "clash-verge-tui binary"

[[bin]]
name = "clash-verge-tui"
path = "src/main.rs"

[dependencies]
cvt-core = { path = "../cvt-core", version = "0.8.0" }
cvt-tui = { path = "../cvt-tui", version = "0.8.0" }
anyhow.workspace = true
clap.workspace = true
chrono.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_norway.workspace = true
futures-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
unicode-width.workspace = true
reqwest.workspace = true
flate2.workspace = true
tar.workspace = true
sha2.workspace = true
semver = "1.0.28"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
